# Generated by Django 5.1.6 on 2025-04-25 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_defined_fields', models.JSONField()),
                ('personal_information', models.JSONField()),
                ('overview', models.JSONField()),
                ('education', models.JSONField()),
                ('professional_experience', models.JSONField()),
                ('skills', models.JSONField()),
                ('referees', models.JSONField()),
                ('extras', models.JSONField()),
                ('certificates', models.JSONField()),
                ('languages', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
