# Generated by Django 5.1.6 on 2025-03-25 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_defined_fields', models.JSONField(default=dict)),
                ('personal_information', models.JSONField(default=dict)),
                ('overview', models.JSONField(default=dict)),
                ('education', models.JSONField(default=list)),
                ('professional_experience', models.JSONField(default=list)),
                ('skills', models.JSONField(default=dict)),
                ('referees', models.JSONField(default=list)),
                ('extras', models.JSONField(default=list)),
                ('certificates', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('resume_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_model', to='resumes.resumemodel')),
            ],
        ),
    ]
