# Generated by Django 5.1.6 on 2025-04-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedatamodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 8, 35, 46, 396226, tzinfo=datetime.timezone.utc)),
        ),
    ]
