# Generated by Django 5.1.6 on 2025-04-26 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumedatamodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedatamodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
